name: Gerar APK Android

on:
  push:
    branches: [ "main", "master", "principal" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: gradle

    - name: Configurar Android SDK
      uses: android-actions/setup-android@v3

    - name: Instalar SDK necessário
      run: |
        sdkmanager "platform-tools" \
                   "platforms;android-33" \
                   "build-tools;33.0.2"

    - name: Dar permissão no gradlew
      run: chmod +x gradlew

    - name: Compilar APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Salvar APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/*.apk
