name: Gerar APK Android

on:
  push:
    branches: [ "main", "master", "principal" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Criar Gradle Wrapper
      run: gradle wrapper

    - name: Dar permissão de execução
      run: chmod +x gradlew

    - name: Compilar APK
      run: ./gradlew assembleDebug

    - name: Salvar APK para Download
      uses: actions/upload-artifact@v4
      with:
        name: copiloto-apk
        path: "**/build/outputs/apk/debug/*.apk"
